name: github pages

on:
  push:
    branches:
    - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
